# Generated by Django 5.2.5 on 2025-09-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='cidade',
            new_name='jurisdicao',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='nome_real',
        ),
        migrations.AddField(
            model_name='hero',
            name='poderes_secundarios',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
